export const SEARCH_FILMS = 'SEARCH_FILMS';

export const LOAD_BY_SEARCH_VALUE = 'LOAD_BY_SEARCH_VALUE';

export const LOAD_BY_ID = 'LOAD_BY_ID';

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';

export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';

export const SET_FILM_DESCRIPTION = 'SET_FILM_DESCRIPTION';

export const SHOW_MORE_FILMS = 'SHOW_MORE';

export const LOAD_MORE_FILMS = 'LOAD_MORE_FILMS';

export const INCREMENT_PAGE = 'INCREMENT_PAGE';

export const SET_NUMBER_OF_RESULTS = 'SET_NUMBER_OF_RESULTS';
