export const SEARCH_FILMS = 'SEARCH_FILMS';

export const LOAD_DATA = 'LOAD_DATA';

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';

export const CHANGE_ERROR_STATUS = 'CHANGE_ERROR_STATUS';

export const SET_FILM_DESCRIPTION = 'SET_FILM_DESCRIPTION';
